server:
  port: 8081
spring:
  application:
    name: product

  datasource:
    url: jdbc:mysql://localhost:3306/product-svc
    username: root
    password: root

#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: false
#        jdbc:
#          batch_size: 10
#        order_inserts: true
#        order_updates: true
#        generate_statistics: true
  #        use_sql_comments: true
  #        generate_statistics: true

  logging:
    level:
  #    org.hibernate.SQL: DEBUG
  #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  #    org.springframework.web: DEBUG
#      org.hibernate.jdbc.BatchingBatch: DEBUG
  #    root: DEBUG
      org.apache.kafka: DEBUG
  kafka:
    bootstrap-servers: localhost:29092
#    consumer:
#      group-id: order-inventory-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#        spring.json.type.mapping: inventoryEvent:com.laundry.product.event.InventoryEvent

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


